# Generated by Django 5.2.7 on 2025-10-29 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона, например +71234567890.', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Имя и фамилия могут содержать только буквы и дефис (2–30 символов).', regex='^[А-Яа-яA-Za-zЁё-]{2,30}$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Имя и фамилия могут содержать только буквы и дефис (2–30 символов).', regex='^[А-Яа-яA-Za-zЁё-]{2,30}$')], verbose_name='Фамилия'),
        ),
    ]
